config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :feedings, except: [:show]

  get 'feedings/index' => 'feedings#index'
  get '/session' => 'feedings#index'

  post '/feednow' => 'feedings#feed_now', as: 'feed_now'
  post '/togglefeeding' => 'feedings#toggle_feeding', as: 'toggle_feeding'

  root 'feedings#index'

  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
	belongs_to :feeding
end

app/models/feeding.rb
class Feeding < ApplicationRecord
	has_many :emails
	has_many :feeding_times
end

app/models/feeding_time.rb
class FeedingTime < ApplicationRecord
  belongs_to :feeding
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/feedings_controller.rb
require 'byebug'
class FeedingsController < ApplicationController


	def whenever_friendly!(input)
		if input != 'None'
			input[-3] += ' '
			input.gsub!(/\./,':')
		end
	end


	def index
		if signed_in? 
		else
			@time_selection = []
			redirect_to sign_in_path
		end
	end

	def toggle_feeding
		if params[:status] == "on"
			Feeding.first.automated_feeding = true
		elsif params[:status] == "off"
			Feeding.first.automated_feeding = false
		end
		Feeding.first.save
		redirect_to root_path
	end


	def new
		@feeding = Feeding.new
	end

	def create
	  @feeding = Feeding.new(feeding_params)
	   if @feeding.save
	   	redirect_to root_path, notice: "Saved"
	   else	
	   	redirect_to new_feedings_path, notice: "Failed"
	   end
	end


	def edit
	end

	def update

		@time_conversion = {
		'None' => nil,
		'12.00am' => (946684800+1800*0),
		'12.30am' => (946684800+1800*1),
		'1.00am' => (946684800+1800*2),
		'1.30am' => (946684800+1800*3),
		'2.00am' => (946684800+1800*4),
		'2.30am' => (946684800+1800*5),
		'3.00am' => (946684800+1800*6),
		'3.30am' => (946684800+1800*7),
		'4.00am' => (946684800+1800*8),
		'4.30am' => (946684800+1800*9),
		'5.00am' => (946684800+1800*10),
		'5.30am' => (946684800+1800*11),
		'6.00am' => (946684800+1800*12),
		'6.30am' => (946684800+1800*13),
		'7.00am' => (946684800+1800*14),
		'7.30am' => (946684800+1800*15),
		'8.00am' => (946684800+1800*16),
		'8.30am' => (946684800+1800*17),
		'9.00am' => (946684800+1800*18),
		'9.30am' => (946684800+1800*19),
		'10.00am' => (946684800+1800*20),
		'10.30am' => (946684800+1800*21),
		'11.00am' => (946684800+1800*22),
		'11.30am' => (946684800+1800*23),
		'12.00pm' => (946684800+1800*24),
		'12.30pm' => (946684800+1800*25),
		'1.00pm' => (946684800+1800*26),
		'1.30pm' => (946684800+1800*27),
		'2.00pm' => (946684800+1800*28),
		'2.30pm' => (946684800+1800*29),
		'3.00pm' => (946684800+1800*30),
		'3.30pm' => (946684800+1800*31),
		'4.00pm' => (946684800+1800*32),
		'4.30pm' => (946684800+1800*33),
		'5.00pm' => (946684800+1800*34),
		'5.30pm' => (946684800+1800*35),
		'6.00pm' => (946684800+1800*36),
		'6.30pm' => (946684800+1800*37),
		'7.00pm' => (946684800+1800*38),
		'7.30pm' => (946684800+1800*39),
		'8.00pm' => (946684800+1800*40),
		'8.30pm' => (946684800+1800*41),
		'9.00pm' => (946684800+1800*42),
		'9.30pm' => (946684800+1800*43),
		'10.00pm' => (946684800+1800*44),
		'10.30pm' => (946684800+1800*45),
		'11.00pm' => (946684800+1800*46),
		'11.30pm' => (946684800+1800*47)}
		@feed_duration = Feeding.first
		@email = Email.first
		@feed_time = FeedingTime.first

		@cron_feeding_times = []

		@feed_duration.feeding_duration = params[:feeding_duration]

		feed_file = File.open("../feed.py",'w')
		feed_file.puts 'import RPi.GPIO as GPIO'
		feed_file.puts 'import time'
		feed_file.puts 'import logging'
		feed_file.puts 'import datetime'
		feed_file.puts 'GPIO.setmode(GPIO.BCM)'
		feed_file.puts 'GPIO.setwarnings(False)'
		feed_file.puts 'GPIO.setup(23,GPIO.OUT)'
		feed_file.puts 'GPIO.setup(18,GPIO.OUT)'
		feed_file.puts 'GPIO.setup(26,GPIO.OUT)'
		feed_file.puts '#Power on motor'
		feed_file.puts 'GPIO.output(23,GPIO.HIGH)'
		feed_file.puts "time.sleep(#{params[:feeding_duration]})"
		feed_file.puts 'GPIO.output(23,GPIO.LOW)'
		feed_file.puts '# 3 Beeps'
		feed_file.puts 'GPIO.output(26,GPIO.HIGH)'
		feed_file.puts 'time.sleep(0.2)'
		feed_file.puts 'GPIO.output(26,GPIO.LOW)'
		feed_file.puts 'time.sleep(0.2)'
		feed_file.puts 'GPIO.output(26,GPIO.HIGH)'
		feed_file.puts 'time.sleep(0.2)'
		feed_file.puts 'GPIO.output(26,GPIO.LOW)'
		feed_file.puts 'time.sleep(0.2)'
		feed_file.puts 'GPIO.output(26,GPIO.HIGH)'
		feed_file.puts 'time.sleep(0.2)'
		feed_file.puts 'GPIO.output(26,GPIO.LOW)'
		feed_file.puts 'time.sleep(0.2)'
		feed_file.puts 'logging.basicConfig(filename="pitch_woofles/log/cron.log",level=logging.DEBUG)'
		feed_file.puts 'logging.debug(datetime.datetime.now())'
		feed_file.close

		@email.email1 = params[:email1]
		@email.email2 = params[:email2]

		params[:feeding_time_1] == 'None' ? (@feed_time.feeding_time_1 = nil) : (@feed_time.feeding_time_1 = Time.at(@time_conversion[params[:feeding_time_1]]))
		params[:feeding_time_2] == 'None' ? (@feed_time.feeding_time_2 = nil) : (@feed_time.feeding_time_2 = Time.at(@time_conversion[params[:feeding_time_2]]))
		params[:feeding_time_3] == 'None' ? (@feed_time.feeding_time_3 = nil) : (@feed_time.feeding_time_3 = Time.at(@time_conversion[params[:feeding_time_3]]))
		params[:feeding_time_4] == 'None' ? (@feed_time.feeding_time_4 = nil) : (@feed_time.feeding_time_4 = Time.at(@time_conversion[params[:feeding_time_4]]))
		

		if params[:feeding_time_1] != 'None'
			@cron_feeding_times.push(whenever_friendly!(params[:feeding_time_1]))
		end

		if params[:feeding_time_2] != 'None'
			@cron_feeding_times.push(whenever_friendly!(params[:feeding_time_2]))
		end

		if params[:feeding_time_3] != 'None'
			@cron_feeding_times.push(whenever_friendly!(params[:feeding_time_3]))
		end

		if params[:feeding_time_4] != 'None'
			@cron_feeding_times.push(whenever_friendly!(params[:feeding_time_4]))
		end

		out_file = File.open("config/schedule.rb",'w')
		out_file.puts 'set :output, "#{path}/log/cron.log"'
		out_file.puts ""
		out_file.puts "every 1.day, at: #{@cron_feeding_times} do"
		out_file.puts '  command "python #{path}/../feed.py"'
		out_file.puts '  command "date"'
		out_file.puts "end"
		out_file.close


		if @feed_time.save && @feed_duration.save && @email.save
			system('whenever --update-crontab')
			redirect_to root_path
		else
			redirect_to root_path
		end
	end

	def destroy	
	end


	def feed_now
		if system("python ../feed_now.py #{params[:feeding_duration]}") 
			if (Feeding.first.notification == true)
				FeedingNotificationMailer.notify_owner(Email.first).deliver
			end
		  	puts "feeding success!"
		  	redirect_to root_path
		else
			puts "feeding failed"
		  	ErrorNotificationMailer.notify_owner(Email.first).deliver
		  	redirect_to root_path
		end
	end


	def feed 
		pyname = 'feed.py'
		if system("python", pyname) 
			if (Feeding.first.notification == true)
				FeedingNotificationMailer.notify_owner(Email.first).deliver
			end
		  	puts "feeding success!"
		else
			puts "feeding failed"
		  	ErrorNotificationMailer.notify_owner(Email.first).deliver
		end
	end



	private
	  # Use callbacks to share common setup or constraints between actions.
	  def set_feeding
	    @feeding = Feeding.find(params[:id])
	  end

	  # Never trust parameters from the scary internet, only allow the white list through.
	  def feeding_params
	    params.require(:feeding, :email, :feeding_time).permit(:automated_feeding,:email1, :email2, :feeding_time_1, :feeding_time_2, :feeding_time_3, :feeding_time_4, :feeding_duration)
	  end

end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to sign_in_path
      else
        redirect_to sign_up_path
      end
    end
  
      private
  
      def user_params
        params.require(:user).permit(:email, :user_name, :pet_name, :password)
      end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedings_helper.rb
module FeedingsHelper
end

app/views/feedings/_edit.html.erb
<% selection = ['None',
	'12.00am','12.30am',
	'1.00am','1.30am',
	'2.00am','2.30am',
	'3.00am','3.30am',
	'4.00am','4.30am',
	'5.00am','5.30am',
	'6.00am','6.30am',
	'7.00am','7.30am',
	'8.00am','8.30am',
	'9.00am','9.30am',
	'10.00am','10.30am',
	'11.00am','11.30am',
	'12.00pm','12.30pm',
	'1.00pm','1.30pm',
	'2.00pm','2.30pm',
	'3.00pm','3.30pm',
	'4.00pm','4.30pm',
	'5.00pm','5.30pm',
	'6.00pm','6.30pm',
	'7.00pm','7.30pm',
	'8.00pm','8.30pm',
	'9.00pm','9.30pm',
	'10.00pm','10.30pm',
	'11.00pm','11.30pm'] %>

<%	@time_conversion = {
		'None' => nil,
		'12.00am' => (946684800+1800*0),
		'12.30am' => (946684800+1800*1),
		'1.00am' => (946684800+1800*2),
		'1.30am' => (946684800+1800*3),
		'2.00am' => (946684800+1800*4),
		'2.30am' => (946684800+1800*5),
		'3.00am' => (946684800+1800*6),
		'3.30am' => (946684800+1800*7),
		'4.00am' => (946684800+1800*8),
		'4.30am' => (946684800+1800*9),
		'5.00am' => (946684800+1800*10),
		'5.30am' => (946684800+1800*11),
		'6.00am' => (946684800+1800*12),
		'6.30am' => (946684800+1800*13),
		'7.00am' => (946684800+1800*14),
		'7.30am' => (946684800+1800*15),
		'8.00am' => (946684800+1800*16),
		'8.30am' => (946684800+1800*17),
		'9.00am' => (946684800+1800*18),
		'9.30am' => (946684800+1800*19),
		'10.00am' => (946684800+1800*20),
		'10.30am' => (946684800+1800*21),
		'11.00am' => (946684800+1800*22),
		'11.30am' => (946684800+1800*23),
		'12.00pm' => (946684800+1800*24),
		'12.30pm' => (946684800+1800*25),
		'1.00pm' => (946684800+1800*26),
		'1.30pm' => (946684800+1800*27),
		'2.00pm' => (946684800+1800*28),
		'2.30pm' => (946684800+1800*29),
		'3.00pm' => (946684800+1800*30),
		'3.30pm' => (946684800+1800*31),
		'4.00pm' => (946684800+1800*32),
		'4.30pm' => (946684800+1800*33),
		'5.00pm' => (946684800+1800*34),
		'5.30pm' => (946684800+1800*35),
		'6.00pm' => (946684800+1800*36),
		'6.30pm' => (946684800+1800*37),
		'7.00pm' => (946684800+1800*38),
		'7.30pm' => (946684800+1800*39),
		'8.00pm' => (946684800+1800*40),
		'8.30pm' => (946684800+1800*41),
		'9.00pm' => (946684800+1800*42),
		'9.30pm' => (946684800+1800*43),
		'10.00pm' => (946684800+1800*44),
		'10.30pm' => (946684800+1800*45),
		'11.00pm' => (946684800+1800*46),
		'11.30pm' => (946684800+1800*47)} %>

<% FeedingTime.first.feeding_time_1 == nil ? (previous_selection_1 = []) : (previous_selection_1 = [@time_conversion.index(FeedingTime.first.feeding_time_1.to_i)]) %>
<% FeedingTime.first.feeding_time_2 == nil ? (previous_selection_2 = []) : (previous_selection_2 = [@time_conversion.index(FeedingTime.first.feeding_time_2.to_i)]) %>
<% FeedingTime.first.feeding_time_3 == nil ? (previous_selection_3 = []) : (previous_selection_3 = [@time_conversion.index(FeedingTime.first.feeding_time_3.to_i)]) %>
<% FeedingTime.first.feeding_time_4 == nil ? (previous_selection_4 = []) : (previous_selection_4 = [@time_conversion.index(FeedingTime.first.feeding_time_4.to_i)]) %>



<!-- Large modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bd-modal-lg">Edit  <i class="fas fa-edit"></i></button>

<div class="modal fade bd-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="opacity: 1.0;">
	<!-- Modal content -->
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="card-body">
				<h3 class="display-4 py-3">Settings</h3>
				<%= form_with model: @feeding, url: feedings_path, method: :patch do |f| %>
					
					<hr>
					<h4>Notification</h4>
					<div class="px-5 mx-auto" style="width:90%">
						<p class="text-muted small">Woofles will send an email notification to the following addresses whenever automatic feeding is triggered, or when the it's time for your weekly cleaning</p>
					</div>
					<div class="form-row px-5 my-2">
						<%= f.label :Primary_email, class: 'col-3 align-self-center' %>
					  	<%= f.text_field :email1, type: 'email', class: 'form-control col-9', value: "#{Email.first.email1}" %>
					</div>

					<div class="form-row px-5 my-2">
						<%= f.label :Secondary_email, class: 'col-3 align-self-center' %>
					  	<%= f.text_field :email2, type: 'email', class: 'form-control col-9', value: "#{Email.first.email2}" %>
					</div>

					<hr class="my-5">

					<h4>Feeder Settings</h4>
					<p class="text-muted small">Woofles will spin the valve based on the number of seconds</p>

					<div class="form-row px-5 my-2">
						<%= f.label :Feed_Amount, class: 'col-3 align-self-center' %>
						<select name="feeding_duration" id="feeding_time" class="form-control col-9">
					  		<%= options_for_select([Feeding.first.feeding_duration]+[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]) %>
					  	</select>
					</div>

					<hr class="my-5">

					<h4>Feeding Time</h4>
					<p class="text-muted small">Change the default behavior of the Woofles</p>

					<div class="form-row px-5 my-2">
						<%= f.label :feeding_time_1, class: 'col-3 align-self-center' %>
						<select name="feeding_time_1" id="feeding_time" class="form-control col-9">
					  		<%= options_for_select(previous_selection_1+selection) %>
					  	</select>
					</div>

					<div class="form-row px-5 my-2">
						<%= f.label :feeding_time_2, class: 'col-3 align-self-center' %>
						<select name="feeding_time_2" id="feeding_time" class="form-control col-9">
					  		<%= options_for_select(previous_selection_2+selection) %>
					  	</select>
					</div>

					<div class="form-row px-5 my-2">
						<%= f.label :feeding_time_3, class: 'col-3 align-self-center' %>
						<select name="feeding_time_3" id="feeding_time" class="form-control col-9">
					  		<%= options_for_select(previous_selection_3+selection) %>
					  	</select>
					</div>

					<div class="form-row px-5 my-2">
						<%= f.label :feeding_time_4, class: 'col-3 align-self-center' %>
						<select name="feeding_time_4" id="feeding_time" class="form-control col-9">
					  		<%= options_for_select(previous_selection_4+selection) %>
					  	</select>
					</div>

					<hr>

					<div class="submit-field">
					  <button type="button" class="btn btn-warning" data-dismiss="modal">Cancel</button>
					  <%= f.submit "Save Changes", class: 'btn btn-primary' %>
					</div>

				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/feedings/index.html.erb
<% log_file = File.open("log/cron.log","r") %>
	<% @updated_at = log_file.ctime %>
<% log_file.close %>

<div class="jumbotron py-3" style="background-color: black;">
	<div class="container">
		<div class="row">
			<div class="col-9">
				<div class="text-left" style="font-family: 'Gamja Flower', cursive;">
					<h1 class="display-4 mx-auto" style="font-family: 'Gamja Flower', cursive; color: white;"><%= Feeding.first.pet_name %>'s Feeder</h1>
					<h4 class="font-weight-bold d-none d-lg-block" style="color: grey;">by WOOFLES Smart Feeder</h4>
				</div>
			</div>
			<div class="col-3 text-right align-self-center">
				<%= button_to 'Log out', sign_out_path, method: :delete, class: 'btn btn-danger btn-lg mx-auto' %>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">


		<!-- Settings -->
		<div class="col-lg-4 col-sm-12 my-4 px-1">
			<div class="card text-center row-eq-height" style="background-color: rgba(255, 255, 255, 0.6);">
				<div class="card-body py-4 my-2" style="height:667px;">
					<h2 class="card-title display-4 my-2" style="font-family: 'Permanent Marker', cursive;">Settings</h2>
					</br>
					<div class="p-2 mx-auto align-items-center text-center" style="border: 2px solid grey; width:10rem; height:10rem; border-radius: 50%; transform: rotate(40deg)">
						<i class="fas fa-cogs py-3 m-3" style="font-size:4.5rem; height:100%"></i>
					</div>
					</br>
		        	<div class="pt-3">
			        	<h5>Automatic Feeding</h5>
				        	<label class="switch">
								  <input id="feedcheckbox" type="checkbox" name="automated_feeding"<%= Feeding.first.automated_feeding == true ? ('checked') : ('') %> id="toggleFeeding">
								  <span id="span" class="slider round"></span>
							</label>
				        	<%= form_with(url: toggle_feeding_path, method: :post, class: 'd-none') do |f| %>
				        		<%= f.text_field :status, value:"on", id:"statusValue" %>
								<%= f.submit "save", class: 'btn btn-primary', id:'hiddenbtn' %>
							<% end %>
		        	</div>
		        	<hr class="px-5">
		        	<div class="pt-3">
			        	<h5>Cleaning Reminder</h5>
			        	<p class="small text-muted px-5"> Woofles will remind you to clean the feeder once a week</p>

			        	<label class="switch">
						  <input type="checkbox" <%= Feeding.first.cleaning_day != '' ? ('checked') : ('') %> id="toggleFeeding">
						  <span class="slider round"></span>
						</label>
		        	</div>
				</div>
			</div>
		</div>


		<!-- Report -->
		<div class="col-lg-4 col-sm-12 my-4 px-1">
			<div class="card text-center row-eq-height" style="background-color: rgba(255, 255, 255, 0.6);">
				<div class="card-body py-4 my-2" style="height:667px;">
					<h2 class="card-title display-4 my-2" style="font-family: 'Permanent Marker', cursive;">Overview</h2>
					</br>
					<div class="p-2 mx-auto align-items-center text-center" style="border: 2px solid grey; width:10rem; height:10rem; border-radius: 50%; transform: rotate(20deg)">
						<i class="fas fa-clipboard-list py-2 m-3" style="font-size:5rem; height:100%"></i>
					</div>
					</br>
		        	<h5 class="pt-3"><%= Feeding.first.pet_name %> was last fed at</h5>
		        	<h5><%= @updated_at.to_s[0..15] %></h5>

		        	<hr class="my-3">

		        	<h5><%= Feeding.first.pet_name %>'s feeding time</h5>
		        	<%= FeedingTime.first.feeding_time_1.to_s[11..15] == nil ? () : raw("<p class='d-inline mx-3'>#{FeedingTime.first.feeding_time_1.to_s[11..15]}</p>") %>
		        	<%= FeedingTime.first.feeding_time_2.to_s[11..15] == nil ? () : raw("<p class='d-inline mx-3'>#{FeedingTime.first.feeding_time_2.to_s[11..15]}</p>") %>
		        	<%= FeedingTime.first.feeding_time_3.to_s[11..15] == nil ? () : raw("<p class='d-inline mx-3'>#{FeedingTime.first.feeding_time_3.to_s[11..15]}</p>") %>
		        	<%= FeedingTime.first.feeding_time_4.to_s[11..15] == nil ? () : raw("<p class='d-inline mx-3'>#{FeedingTime.first.feeding_time_4.to_s[11..15]}</p>") %>

		        	<hr class="my-3">

		        	<h5>Feeding Duration</h5>
		        	<p><%= Feeding.first.feeding_duration%> seconds</p>
					<%= render partial: 'feedings/edit' %>
				</div>
			</div>
		</div>


		<!-- Manual Feeding -->
		<div class="col-lg-4 col-sm-12 my-4 px-1">
			<div class="card text-center row-eq-height" style="background-color: rgba(255, 255, 255, 0.6); height:685px;">
				<div class="card-body py-4 my-2" style="height:667px;">
					<h2 class="card-title display-4 my-2" style="font-family: 'Permanent Marker', cursive;">Feed</h2>
					</br>
					<div class="p-2 mx-auto align-items-center text-center" style="border: 2px solid grey; width:10rem; height:10rem; border-radius: 50%; transform: rotate(40deg)">
						<i class="fas fa-bone py-4 m-3" style="font-size:4rem; height:100%"></i>
					</div>
					</br>


					<div class="px-4">

					<%= form_with(url:feed_now_path, method: :post) do |f| %>

						<h5 class="p-3">How much would you like to feed <%= Feeding.first.pet_name %>?</h5>
						</br>
						<select class="custom-select" id="inlineFormCustomSelect" name="feeding_duration">
							<option selected value="<%= Feeding.first.feeding_duration %>"><%= Feeding.first.feeding_duration %> seconds</option>
							<option value="1">1 seconds</option>
							<option value="2">2 seconds</option>
							<option value="3">3 seconds</option>
							<option value="4">4 seconds</option>
							<option value="5">5 seconds</option>
							<option value="6">6 seconds</option>
							<option value="7">7 seconds</option>
							<option value="8">8 seconds</option>
							<option value="9">9 seconds</option>
							<option value="10">10 seconds</option>
							<option value="11">11 seconds</option>
							<option value="12">12 seconds</option>
							<option value="13">13 seconds</option>
							<option value="14">14 seconds</option>
							<option value="15">15 seconds</option>
						</select>
						</br>
						</br>

						<div class="submit-field">
							<%= f.submit "Feed #{Feeding.first.pet_name}", class: 'btn btn-primary' %>
						</div>
					<% end %>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>

app/views/feedings/new.html.erb
Headline

<%= render partial: 'feedings/form' %>

Footer

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Woofles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Gamja+Flower|Markazi+Text|Permanent+Marker|Poor+Story" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </body>
</html>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <div class="text-field">
      <%= form.label :your_name %>
      <%= form.text_field :user_name %>
    </div>

    <div class="text-field">
      <%= form.label :pet_name %>
      <%= form.text_field :pet_name %>
    </div>

    <div class="text-field">
      <%= form.label :email %>
      <%= form.text_field :email, type: 'email' %>
    </div>

    <div class="password-field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>